seslib: make all str-type settings default to the empty string
When string variables are set to None, we can easily fall into a trap
like this:

  File "/home/tom/devel/suse/sesdev/seslib/__init__.py", line 1082, in generate_vagrantfile
      if self.settings.ceph_salt_git_branch.startswith('origin/pr/'):
  AttributeError: 'NoneType' object has no attribute 'startswith'

Fixes: https://github.com/SUSE/sesdev/issues/216
Signed-off-by: Nathan Cutler <ncutler@suse.com>